# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Mysql

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Mysql
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306

    # This keyword is used to define the build strategy for your workflow. In this case, it's specifying a matrix strategy
    strategy:
      # This sub-keyword defines a matrix build strategy, which allows you to run your job in multiple configurations
      matrix:
        # This sub-keyword defines the Node.js version to use for the job
        node-version: [18.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use ${{matrix.node-version}} to setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -u${{secrets.MYSQL_USERNAME}} -h${{secrets.MYSQL_HOSTNAME}} -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASENAME }};" || exit 1
          mysql -u${{secrets.MYSQL_USERNAME}} -h${{secrets.MYSQL_HOSTNAME}} -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "USE ${{ secrets.MYSQL_DATABASENAME }};" || exit 1

      - name: Run tests
        env:
          MYSQL_HOSTNAME: ${{secrets.MYSQL_HOSTNAME}}
          MYSQL_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
          MYSQL_DATABASENAME: ${{secrets.MYSQL_DATABASENAME}}
          MYSQL_USERNAME: ${{secrets.MYSQL_USERNAME}}
          SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
          PORT: ${{secrets.PORT}}
        run: npm test .\tests\user.test.js

      - name: Delete Database
        run: |
          mysql -u${{secrets.MYSQL_USERNAME}} -h${{secrets.MYSQL_HOSTNAME}} -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "DROP DATABASE ${{ secrets.MYSQL_DATABASENAME }};" || exit 1
