name: Packer-Build

env:
  MYSQL_HOSTNAME: ${{secrets.MYSQL_HOSTNAME}}
  MYSQL_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
  MYSQL_DATABASENAME: ${{secrets.MYSQL_DATABASENAME}}
  MYSQL_USERNAME: ${{secrets.MYSQL_USERNAME}}
  SALT_ROUNDS: ${{secrets.SALT_ROUNDS}}
  PORT: ${{secrets.PORT}}

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  packer-check:
    name: Packer Build CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -u${{secrets.MYSQL_USERNAME}}  -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASENAME }};" || exit 1
          mysql -u${{secrets.MYSQL_USERNAME}}  -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "USE ${{ secrets.MYSQL_DATABASENAME }};" || exit 1

      - name: Install Nodejs dependencies
        run: npm install

      - name: Run Nodejs tests
        run: npm run test-mysql

      - name: Zip Node.js application
        run: |
          npm run zip

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_PACKER_CREDENTIALS }}
          project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: Get credentials file path
        run: echo $GOOGLE_APPLICATION_CREDENTIALS

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Initialize Packer
        run: |
          cd packer
          packer init .

      - name: Build packer file
        run: |
          FILE="setup.pkr.hcl"
          cd packer
          packer build -force -var "credentials=$GOOGLE_APPLICATION_CREDENTIALS" -var "project_id=${{secrets.GCP_PROJECT_ID}}" -var "MYSQL_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}}" -var "MYSQL_DATABASENAME=${{secrets.MYSQL_DATABASENAME}}" -var "MYSQL_USERNAME=${{secrets.MYSQL_USERNAME}}" -var "MYSQL_HOSTNAME=${{secrets.MYSQL_HOSTNAME}}" -var "SALT_ROUNDS=${{secrets.SALT_ROUNDS}}" -var "PORT=${{secrets.PORT}}" $FILE || exit 1
